### ISSUE TITLE
REST API integration with frontend text view

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend-legacy#108]
Text view pages have 3 sections that each need different data:

**Left:**
Needs segmentnr & segment text for that filename loaded first and displayed in the right order.
Once loaded, each segment gets colors assigned based on the offset values of the parallels for those segments. So this needs the loading of the parallels data based on root_segnr. So all parallels that have a root_segnr starting with that filename. The root_offset_beg and _end determine the colors. 

**Middle:**
When clicked on any colored text in the left, the parallels for that specific text need to be loaded (or they are already there when loaded in the previous step and then just displayed.
Extra info that needs to be loaded here is the segmentnr & segment text for each parallel requested.

**Right:**
When clicked on a parallel, the target text is displayed in the right column. So this needs to load all the segments and segmentnr of the target filename in the right order.
This will also need to load all parallels data that source and target have together (so source = root_segnr and target = parsegnr).

Question is if loading of parallels data should be done on the basis of current filters or done all at once and filtered at the frontend.

**Comment by TrebuhD** [comment]
Closing this, as it seems to be complete.
