### ISSUE TITLE
REST API integration with frontend table view (formerly segment view)

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend-legacy#110]
The segment view table needs to have all segments of the requested filename loaded incl. segmentnr, segment and parallels data. This also needs all segments of the requested parallels loaded as well. 

Question here is if it would make sense to have only those in the viewport loaded first and then rest afterwards otherwise it might take a very long time. This also depends a lot on requested sorting and filters.

**Comment by ayya-vimala** [comment]
Here is some AQL for this one:

```
LET parallel_array = FLATTEN(
    FOR parallel IN parallels
        LET root = (
            RETURN(SPLIT(parallel.root_segnr[0],':'))
            )[0]
        FILTER root[0] == @task
        
        LET filtertest = (
            FOR item IN @target
                RETURN REGEX_TEST(parallel.parsegnr[0], item)
            )
        LET filternr = (@target != []) ? POSITION(filtertest, true) : true
        FILTER filternr == true
        FILTER parallel.probability >= @probability
        FILTER parallel.parlength >= @quotelength
        FILTER parallel['co-occ'] <= @cooccurence
        SORT parallel.@sortorder
        RETURN {rootsegnrs : parallel.root_segnr,
                rootoffsets: [parallel.root_offset_beg,parallel.root_offset_end],
                parsegnrs : parallel.parsegnr,
                paroffsets: [parallel.par_offset_beg,parallel.par_offset_end]}
    )
    
LET full_parallel_array = (
    FOR parallel_item IN parallel_array
        LET full_text = (
            RETURN MERGE(
                FOR rootsegnr IN parallel_item.rootsegnrs
                        LET rootoffsetbeg = (rootsegnr == FIRST(parallel_item.rootsegnrs)) ? parallel_item.rootoffsets[0] : 0
                        LET rootoffsetend = (rootsegnr == LAST(parallel_item.rootsegnrs)) ? parallel_item.rootoffsets[1] : -1
                        LET segmentitem = DOCUMENT(@@language, rootsegnr)
                        LET segmentarray = [segmentitem.segment,rootoffsetbeg,rootoffsetend]
                        RETURN {[rootsegnr]: segmentarray}
                )
        )
        LET full_par_text = (
            RETURN MERGE(
                FOR parsegnr IN parallel_item.parsegnrs
                        LET paroffsetbeg = (parsegnr == FIRST(parallel_item.parsegnrs)) ? parallel_item.paroffsets[0] : 0
                        LET paroffsetend = (parsegnr == LAST(parallel_item.parsegnrs)) ? parallel_item.paroffsets[1] : -1
                        LET parsegmentitem = DOCUMENT(@@language, parsegnr)
                        LET parsegmentarray = [parsegmentitem.segment,paroffsetbeg,paroffsetend]
                        RETURN {[parsegnr]: parsegmentarray}
                )
        )
        RETURN [full_text,full_par_text]
    )

RETURN full_parallel_array
```

**Comment by ayya-vimala** [comment]
I'm parking @sebastian-nehrdich's remarks here because it was in another issue:

all parallels for a given text sorted by either:
Position as they occur in the main text (= sort by "root_pos_beg")
Position as they occur in the parallel text. This key can be constructed by concatting the filename of the quoted text and a padded version of the par_pos_beg key. The filename of the quoted text can be acquired with a regex on the par_segnr (everything before the ":" is the filename). if the par_segnr key is "T06TD4023E:8" and the par_pos_beg key is 25204623, the resulting alphanumerical key for this sorting method would be "T06TD4023E0025204623". the padding of the position number with zeros is just to make sure that we keep the order also for smaller numbers. The reason why we add the textname in front of the number is because in this way, the order is guaranteed to be according to the catalog of the Tibetan/Chinese/Pāli canon).
By length (key = par_length) starting with longest
By length starting with shortest
I have already implemented these sorting strategies on the JSON data in Javascript, so for a quick reference this is what is happening here between line 67 and 95: https://github.com/ayya-vimala/pali-networks/blob/102-load-new-jsons/src/views/options/segment-view.js
We would need to fill in the corresponding seg_text-data for the root and the parallel so we can reconstruct the original text.
linked to the previous point: It would be actually great to receive the seg_texts items for both root and parallel from the database by querying for strings that are in the range between their first and last segment_nr (so first and last item of "par_segnr" and "root_segnr"). We could use the "position" key in the root_segnr collection for this because that key guarantees the order of the elements.
I wonder if it is possible to receive the results of the queries in chunks. At the moment, I am only rendering the top 200 results of the results and render more as one scrolls down. It would be great to have the queries behave in the similar way, so first just transfer the first 200 results and successively ask for 'the next 200' as one is scrolling down.

**Comment by sebastian-nehrdich** [comment]
I suggest to close this.
