### ISSUE TITLE
REST API integration with frontend numbers view

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend-legacy#111]
Numbers view only needs to have the parallels data loaded and display the numbers based on sorting and filtering.

**Comment by ayya-vimala** [comment]
The numbers view load is here:
https://github.com/ayya-vimala/pali-networks/blob/master/src/views/options/number-view.js
Basically the context.task is the number of the file that it wants.
context.inputData is the old json data that are loaded. So that one needs to be blocked out here and replaced by a loading of the data we need and then the whole things needs to be re-writen accordingly.

Needed for this view display is:
par_segnr
root_segnr

But these values have to be filtered first so only those values where there is a certain value in:
score
par_length
co-occ

And then the output has to be sorted on either:
root_segnr
or par_length
or par-segnr

The display shows each root-segnr separate so not in an array while the par_segnr become a range like XXX:10-12 (the par_segnr array itself is converted to a range)

**Comment by ayya-vimala** [comment]
The filter function in JS looks like this:
```
export function checkFilters(
  toCheckItems,
  probability,
  quoteLength,
  limitCollection,
  cooccurance
) {
  let collectionFileSelected =
    !limitCollection || !limitCollection[0]
      ? true
      : checkIfItemInArray(toCheckItems.parsegnr[0], limitCollection);
  if (
    toCheckItems.probability >= probability &&
    collectionFileSelected &&
    toCheckItems.parlength >= quoteLength &&
    toCheckItems['co-occ'] <= cooccurance
  ) {
    return true;
  } else {
    return false;
  }
}

function checkIfItemInArray(checkitem, limitCollection) {
  let itemFound = false;
  limitCollection.forEach(item => {
    if (checkitem.includes(item)) {
      itemFound = true;
    }
  });
  return itemFound;
}

Note that `score` and `probability` are synonyms of each other. Recently Sebastian changed this from probability to score.
```

**Comment by ayya-vimala** [comment]
@TrebuhD - I have written a bit of AQL for this one. Maybe just get it into just one list or so - I could not figure out how to do this. Also as a bit of an exercise for me. Some of the values might have changed a bit depending on how Sebastian changed the input files but the general idea remains the same.

```
FOR parallel IN parallels
    LET root = (
        RETURN(SPLIT(parallel.root_segnr[0],':'))
        )[0]
    FILTER root[0] == @task
    LET filternr = (@target != '') ? REGEX_TEST(parallel.parsegnr[0], @target) : true
    FILTER filternr == true
    FILTER parallel.probability >= @probability
    FILTER parallel.parlength >= @quotelength
    FILTER parallel['co-occ'] <= @cooccurence
    SORT parallel.@sortorder
    RETURN MERGE(
        FOR rootnr IN parallel.root_segnr
            RETURN {[rootnr] : parallel.parsegnr}
            )
```

**Comment by TrebuhD** [comment]
I cannot see how the numbers view works. Is there a working link I can check?

**Comment by ayya-vimala** [comment]
Development branch on Tibetan --> T06TD4023E

**Comment by ayya-vimala** [comment]
I've adapted the above AQL a bit so the output is now something like:
```
    {
      "rootsegnrs": "T06TD4021E:19_0–22_0",
      "parsegnrs": "T02TD1848E:8344_0–8347_0"
    },
    {
      "rootsegnrs": "T06TD4021E:21_0–24_0",
      "parsegnrs": "T06TD4027E:62_0–65_0"
    },
```
But feel free to change it if not useful.
Basically this would display in a table like (if sorted on root text number):

<table>
<tr>
<th>Root</th>
<th>T02</th>
<th>T06</th>
</tr>
<tr>
<td>T06TD4021E:19_0–22_0</td>
<td>T02TD1848E:8344_0–8347_0</td>
<td></td>
</tr>
<tr>
<td>T06TD4021E:21_0–24_0</td>
<td></td>
<td>T06TD4027E:62_0–65_0</td>
</tr>
</table>

**Comment by ayya-vimala** [comment]
Probably needs some explanation on terms. I have gone from the premise that the database will use the same notation as Sebastian's latest files so there are a few changes, post notably that `probability` is now called `score`, there are some position tags added in the parallels and also in the segments and some tags have an extra `_` to make it consistent.

```
For the input of the above AQL you need to know the following:
@task = string. source text that is being requested (also called root) like for instance we want to generate the table for T06TD4021E as task.
@target = the filter options for the two multi-select-combo-boxes. Here you can filter for which texts or collections you want the results for. This is an array. So for instance, somebody who wants all the parallels between the root text and T06TD4027E as well as the collection T02 can give this in and the input array becomes: ["T06TD4027E","T02"]. So @target is always an array also with only one item in it. If no target is set, this filter is automatically for all texts.
@score = value of the score/probability filter in int
@quotelength = value of the length filter in int that has to match with the par_length value in the db.
@cooccurance = value of the co-occurance filter in int to match with the co-occ value in the db
@sortorder = a value string that matches with a value in the database. The input can be either 'par-length', 'root_pos_beg' or 'par_pos_beg'. 'par_length' should have the option to descend ascending or descending
```

**Comment by ayya-vimala** [comment]
A few things:
1. `collections[0] returns Chinese collection names for the tooltips on the table header for T01-T16. This should be the Tibetan ones. Note that T numbers are used in 3 different languages.
2. Empty rows and columns are to be removed after filtering.
3. At least on my screen the table height is just a little too large.

We decided to drop the sortorder-dropdown on this element so that does not need to be taken into account. It can just be sorted on segment number as it is.

**Comment by sebastian-nehrdich** [comment]
When I checked the branch I also noted that the keys in the data are still the old ones (probability instead of score etc.). This might be because the older jsons have been used to populate the database at that point, so we should be aware that things will break here when we update the data!

**Comment by TrebuhD** [comment]
Thank you for the bug descriptions, guys. I will create a bug ticket and work on it today.

**Comment by ayya-vimala** [comment]
@TrebuhD I'm happy to write a bug ticket for this now I'm working on the Zenboard ...

**Comment by ayya-vimala** [comment]
@TrebuhD I have difficulty displaying this branch for the bug fixes of the numbers view.
First it complains about:

> ./src/index.js
> Module not found: Error: Can't resolve 'normalize.css' in '/home/suttacentral/pali-networks/src'

When commenting out import 'normalize.css'; in index.js it works but it cannot display the files as per error message:

![Screenshot from 2019-09-09 08-52-12](https://user-images.githubusercontent.com/49606945/64514622-4b100780-d2eb-11e9-8a88-a521878f6a50.png)

**Comment by TrebuhD** [comment]
I think this is now done. Closing but feel free to reopen if needed.
