### ISSUE TITLE
REST API integration with frontend visual view

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend-legacy#112]
The Google Graphs webcomponent needs a very specific set of data. For this we basically need to count the number of parallels from root --> parallel (not the other way around) depending on the selected input collection and on the collection that is clicked at in the graph itself on both sides.

So for instance there are some intial collections in the dropdowns. F.I. Tengyur --> Kangyur.
This counts all parallels for the various Tengyur collections i.e (tibetan T01-T16) to the various Kangyur collections (K01-K13) and loads that in an array of arrays with the format  `   [source,target,nr_parallels],` like this:
`[
        "T09",
        "K12",
        4208
    ],`

Then when somebody clicks on an element of that collection on either the right side or the left side, it needs to load that one and count again.
So If they click on T09 as in the example above, this opens up to it's individual components and loads an array with arrays for for each filename in T09:
`    [
        "T09TD4152E",
        "K12",
        304
    ],` 

etc.

**Comment by ayya-vimala** [comment]
The element should work on the basis of length and not number of parallels.

**Comment by TrebuhD** [comment]
Is this complete?

**Comment by TrebuhD** [comment]
@ayya-vimala I'm closing this as it seems to be complete. Feel free to reopen and transfer to the new repo if it's not.
