### ISSUE TITLE
REST API Integration with frontend combo boxes

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend-legacy#114]
All the combo boxes use the menu data. So that is the initial selection combo-box as well as the two filtering combo-boxes. These are in utility/generate-filters.js and generate-menu.js

**Comment by TrebuhD** [comment]
Question: does the data for the menu combo box come from `/suttalists` or is there another source? I'm looking for JSON data I could use.

I can see the Sanskrit menu has a different structure, do we have a JSON for it?

**Comment by ayya-vimala** [comment]
Yes, it comes from the /suttalists but only the tibetan and chinese. The others are hopelessly outdated.

**Comment by sebastian-nehrdich** [comment]
I will generate new menu jsons very soon and they will all share the same layout. On that occasion I will also generate the collection structure data so that everything is fine.
