### ISSUE TITLE
Move filtering to backend level

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend-legacy#140]
On the number's view, move the filtering to the backend level so the API provides filtered results each time one of the filters changes.

**Comment by ayya-vimala** [comment]
And I also had a look at the filtering query in db_queries.py. This just takes filtering option score,length and co-occ in to account but not the filtering on filename(s) or on collection(s).
So you can filter on one or more specific files, or filter on a collection number or any combination thereof.

I had done this by just comparing the array of requested files and collections (@target) with the first parallel segment number in the array of par_segnr. When no files are selected, the filter is true by default.

>    LET filtertest = (
>         FOR item IN @target
>             RETURN REGEX_TEST(p.par_segnr[0], item)
>         )
>     LET filternr = (@target != []) ? POSITION(filtertest, true) : true
>     FILTER filternr == true

I tried out plugging the above code into your query_file_segments_parallels and that works fine. Unless you have an idea how the above code can be improved. But it seems that calculation times are actually not that bad at all.

**Comment by ayya-vimala** [comment]
@TrebuhD . Although no error messages, it does not seem to want to accept the list/array of filenames for filtering. I think the problem is in the stingify of the parameters, which might not be read properly by the backend. In any case, the backend seems to just ignore this and filter on an empty list.

`const q = '?' + qs.stringify(queryParams, { prefix: '&' });` in `actions.js`

**Comment by TrebuhD** [comment]
@ayya-vimala After merging these 2 PRs, the list filtering should work:

https://github.com/ayya-vimala/buddhanexus/pull/12
https://github.com/ayya-vimala/pali-networks/pull/166
