### ISSUE TITLE
Wrong collection labels on numbers view

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend-legacy#141]
#### Bug Description
`collections[0]` returns Chinese collection names for the tooltips on the table header for T01-T16. This should be the Tibetan ones. Note that T numbers are used in 3 different languages.

#### Steps To Reproduce:

1. Go to 'numbers view on any Tibetan text'
2. Move mouse over the top header to the T numbers
3. See the popup in Chinese instead of Tibetan names.

#### Expected behaviour
When moving the mouse over the top header, the collection names in the right language need to be displayed.

#### Screenshots
![Screenshot from 2019-09-08 11-17-06.png](https://images.zenhubusercontent.com/5cdda43f145f41296ed527b4/7782104e-621c-43fa-9da2-8340f887b945)

**Comment by TrebuhD** [comment]
@ayya-vimala can you check this again? I couldn't reproduce it.

**Comment by ayya-vimala** [comment]
Okay, this looks good now.
