### ISSUE TITLE
Removing empty rows and columns/change number of parallels

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend-legacy#142]
#### Bug Description
There are 2 bugs here, but both might just disappear after the filtering is moved to the backend in issue #140:
There are empty rows and columns after filtering.
The number of parallels after filtering is not correct.

#### Steps To Reproduce:

1. Go to any T06 tibetan file in numbers view
2. Because there are filters applied immediately, it is immediately visible that there are empty rows and columns.
3. When changing filter settings, more or less rows and columns are empty.
4. When changing the filter settings, the number of parallels at the top remains constant.

**Comment by ayya-vimala** [comment]
I think this is done now automatically by moving the filters to the backend.

**Comment by TrebuhD** [comment]
@ayya-vimala could you check this locally as well? It looks correct on my machine now.

**Comment by ayya-vimala** [comment]
I think this is fine now also.
