### ISSUE TITLE
Bugs in numbers view

### ISSUE THREAD

**Issue by TrebuhD** [BuddhaNexus/buddhanexus-frontend-legacy#146]
- `collections[0] returns Chinese collection names for the tooltips on the table header for T01-T16. This should be the Tibetan ones. Note that T numbers are used in 3 different languages.
- Empty rows and columns are to be removed after filtering.
- The number of parallels after filtering is not correct.
- At least on my screen the table height is just a little too large.

**Comment by TrebuhD** [comment]
@ayya-vimala About the first point, do you mean these? At least in the Tibetan page, it seems to be correct:
![image](https://user-images.githubusercontent.com/7022085/65390488-d1066680-dd5f-11e9-9889-0d0ced1cb207.png)

**Comment by ayya-vimala** [comment]
That's good like this. Before it was the Chinese ones.

**Comment by ayya-vimala** [comment]
Okay, I'm behind the computer now.
I think this is the sanskrit label and not the tibetan but that depends: did you load-data beforehand? If not, it is possible that you have the old tibetan labels on there and not the new ones, and the old ones are the same as the sanskrit ... just to confuse you. :confused: 
Anyway, the tibetan for T03 should be `SHES PHYIN—Prajñāpāramitā (Perfection of Wisdom)`. All the new Tibetan ones have the tibetan name in front of the sanskrit name.

**Comment by ayya-vimala** [comment]
Okay ... loaded everything and it's fine.
