### ISSUE TITLE
Visual charts

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend-legacy#16]
Integration of visual view with API. 

* Api setup and integration
* Frontend setup
* Testing & Bugfixing

**Comment by sebastian-nehrdich** [comment]
Just a small note on this: Google supplies a web components-version of google-charts: https://www.webcomponents.org/element/@google-web-components/google-chart
I didn't look deeply into it yet, but has a sankey-visualization according to the docs. We might be able to use this?

**Comment by ayya-vimala** [comment]
Thanks for the tip. Will look into it at some point after Paris!
