### ISSUE TITLE
Not all segments are displayed in Numbers view

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend-legacy#170]
#### Bug Description
The numbers view receives the correct input from the backend, but not all segments are displayed. Also, segments do not seem to be in order, even though the backend gives the segments in the right order.

#### Steps To Reproduce:

1. Go to 'pali/numbers/dn1'
2. See screenshot: The backend has given back segment number dn1:1.1.2 but in the table not all items are displayed, for instance the first one: an4.36:1.2 and others.
The backend has given back segment number dn1:1.1.3 but that is not displayed at all.

#### Expected behaviour
Whatever the backend gives back should be displayed in the same order and all items should be displayed in the table.

#### Screenshots
![Screenshot from 2019-09-24 15-10-20.png](https://images.zenhubusercontent.com/5cdda43f145f41296ed527b4/7463819b-937d-43c6-8d38-f05055cfb83d)

**Comment by TrebuhD** [comment]
@ayya-vimala same here, should be fixed
