### ISSUE TITLE
Numbers view headers not in correct order

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend-legacy#171]
#### Bug Description
Collections and collection labels in the header of the table in numbers view are in alphabetical order, not in order of collection as in 

#### Steps To Reproduce:

1. Go to ''pali/numbers/dn1'
2. See the collection header start with an and it should be in the order as in pli-collections.json
 
#### Expected behaviour
Headers for collections should be in order or collections

**Comment by TrebuhD** [comment]
@ayya-vimala this seems to be fixed, correct?
