### ISSUE TITLE
Loading larger files too slow

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend-legacy#178]
#### Bug Description
Doing some tests to load larger files crashed the browser.

#### Steps To Reproduce:

1. Load 'T29_T1558' in the backend
2. Try loading the file in frontend chinese
3. After 5 minutes it is still not there and crashes the browser
 
#### Expected behaviour
Need lazy loading or some other way to load only part of the files.

**Comment by sebastian-nehrdich** [comment]
I think we can close this. We still have some files that load slow but that's a problem of the backend and I already made an issue for the backend regarding this problem.
