### ISSUE TITLE
Filter graph data by target collection

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend-legacy#220]
Currently the graph data only displays the distribution across all collections. 
A new multi-select-combo-box with the possible collections has to be implemented to filter on just one collection.

**Comment by sebastian-nehrdich** [comment]
In my eyes this looks pretty good now. Should we keep it open since we might integrate it into Tibetan/Pāli as well? For Pāli, I could imagine that splitting the graph according to the Nikāyas or the Piṭakas could also give interesting results (maybe we have to experiment here what works well).

**Comment by ayya-vimala** [comment]
It has been done some time ago. I think I forgot to close this.
